feat: 🎸 new scaffold of icestark using vite and vue3
ice-lab/vue-materials pull request #38
Opened 2021-12-31 08:17 UTC by maoxiaoke

- [ ]  new scaffold of icestark using vite and vue3.

2022-01-04 07:18 UTC, imsobear requested changes

2022-01-04 07:18 UTC, imsobear commented on scaffolds/icestark-child-app/src/App.vue
> +
多余空行

2022-01-04 07:18 UTC, imsobear commented on scaffolds/icestark-child-app/src/App.vue
> +
上面两个也是，故意的么~~

2022-01-04 07:18 UTC, imsobear commented on scaffolds/icestark-child-app/src/router.ts
> +export default genRoute;
这是 vue 3 里推荐的写法吗？

2022-01-04 07:18 UTC, imsobear commented on scaffolds/icestark-child-app/src/router.ts
> +export default genRoute;
感觉不是很优雅

2022-01-04 07:29 UTC, maoxiaoke commented on scaffolds/icestark-child-app/src/App.vue
> +
<style /> 这里的空格是多余的，已修正

2022-01-04 07:38 UTC, maoxiaoke commented on scaffolds/icestark-child-app/src/router.ts
> +export default genRoute;
推荐的写法应该类似于下面的这种：

```js
const routerHistory = createWebHistory();

const router = createRouter({
  history: routerHistory,
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home,
    }
  ],
});

export default router;
```

这里返回一个函数，原因还是二次加载的时候，由于 router 已经实例化了，获取到第一次实例化的 Router 导致问题

2022-01-05 07:26 UTC, imsobear commented on scaffolds/icestark-child-app/README.md
> +https://icestark-vite-vue.vercel.app/
现在资源都是部署在 vercel 上的？那 oss 那个是不是不需要了？

2022-01-05 07:26 UTC, imsobear commented on scaffolds/icestark-child-app/README.md
> +https://icestark-vite-vue.vercel.app/
vercel 这个怎么部署？本地操作？

2022-01-05 07:26 UTC, imsobear commented on scaffolds/icestark-framework-app/README.md
> +https://icestark-vite-vue.vercel.app/
主应用跟子应用同一个 url？

2022-01-05 07:26 UTC, imsobear commented on scaffolds/icestark-child-app/src/router.ts
> +export default genRoute;
是不是放到 main 里面？这里只返回 routes，在 mount() 里面 createWebHistory

2022-01-05 07:37 UTC, imsobear commented on scaffolds/icestark-child-app/src/router.ts
> +// https://zhuanlan.zhihu.com/p/138444490
这个链接放在这里怪怪的

2022-01-05 07:37 UTC, imsobear commented on scaffolds/icestark-child-app/src/router.ts
> +import renderNotFound from '@ice/stark-app/lib/renderNotFound';
这块后续怎么更好的分层可以规划设计下，比如不再区分 app

- @ice/stark：框架无关的 API
- @ice/stark-react：AppRouter、AppLink 等
- @ice/stark-vue

2022-01-05 07:37 UTC, imsobear commented on scaffolds/icestark-framework-app/index.html
> +    <title>Vite App</title>
标题优化下

2022-01-05 07:37 UTC, imsobear commented on scaffolds/icestark-framework-app/src/App.vue
> +        console.log('fdsfsdf', activeApps)
哈？

2022-01-06 06:07 UTC, maoxiaoke commented on scaffolds/icestark-child-app/src/router.ts
> +// https://zhuanlan.zhihu.com/p/138444490
done

2022-01-06 06:13 UTC, maoxiaoke commented on scaffolds/icestark-framework-app/index.html
> +    <title>Vite App</title>
done

2022-01-06 06:48 UTC, maoxiaoke commented on scaffolds/icestark-framework-app/README.md
> +https://icestark-vite-vue.vercel.app/
fixed

2022-01-06 07:11 UTC, maoxiaoke commented on scaffolds/icestark-child-app/src/router.ts
> +import renderNotFound from '@ice/stark-app/lib/renderNotFound';
https://github.com/ice-lab/icestark/issues/508

2022-01-06 07:11 UTC, maoxiaoke commented on scaffolds/icestark-child-app/README.md
> +https://icestark-vite-vue.vercel.app/
本地操作

2022-01-07 06:22 UTC, maoxiaoke commented on scaffolds/icestark-child-app/README.md
> +https://icestark-vite-vue.vercel.app/
后续考虑 ci 而非手动部署的方式

2022-01-07 06:38 UTC, imsobear approved these changes

2022-01-07 07:29 UTC, merged